package com.team.telstra.console.ruledef.console_ruledefinitions;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomStatusOutput implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "customStatusOutput")
	private java.lang.String customStatusOutput;

	public CustomStatusOutput() {
	}

	public java.lang.String getCustomStatusOutput() {
		return this.customStatusOutput;
	}

	public void setCustomStatusOutput(java.lang.String customStatusOutput) {
		this.customStatusOutput = customStatusOutput;
	}

	public CustomStatusOutput(java.lang.String customStatusOutput) {
		this.customStatusOutput = customStatusOutput;
	}

}