package com.team.telstra.console.ruledef.console_ruledefinitions;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PAMStatusInput implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "PAMInputStatus")
	private java.lang.String pamInputStatus;

	public PAMStatusInput() {
	}

	public java.lang.String getPamInputStatus() {
		return this.pamInputStatus;
	}

	public void setPamInputStatus(java.lang.String pamInputStatus) {
		this.pamInputStatus = pamInputStatus;
	}

	public PAMStatusInput(java.lang.String pamInputStatus) {
		this.pamInputStatus = pamInputStatus;
	}

}